site_name: MQ Docs
theme:
  name: 'material'

edit_uri: /moquality/docs/tree/master/mq/docs
repo_name: 'MQ Docs'
repo_url: 'https://github.com/moquality/docs'

markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '⚓'