site_name: MQ Docs
theme:
  name: 'material'

edit_uri: /moquality/docs/tree/master/docs/docs
repo_name: 'MQ Docs'
repo_url: 'https://github.com/moquality/docs'

markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '⚓'

pages:
- "What is MoQuality?": index.md
- Test Recorder:
  - Getting Started: recorder/index.md
  - Setup:
    - Android: recorder/android.md
    - iOS: recorder/ios.md
- CI/CD Integrations:
  - Integrate with Bitrise: integration-ci-cd/bitrise.md
  - Integrate with CircleCI: integration-ci-cd/circleci.md
- FAQ: faq.md
