site_name: MQ Docs
theme:
  name: 'material'

edit_uri: /moquality/docs/tree/master/docs/docs
repo_name: 'MQ Docs'
repo_url: 'https://github.com/moquality/docs'

markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '⚓'

pages:
- "What is MoQuality?": index.md
- Getting Started:
  - Recording Tests in Android: getting-started/android.md
  - Recording Tests in iOS: getting-started/ios.md
  - Web: getting-started/dashboard.md
  - Test Report: getting-started/testreport.md
- Integrate with CI/CD:
  - Integrate with Bitrise: integration-ci-cd/bitrise.md
  - Integrate with CircleCI: integration-ci-cd/circleci.md
